server:
  port: ${PORT:5000}

spring:
  application:
    name: taskManager

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop